services:
  app:
    image: jdncst-portfolio
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3001:3000'
