name: 🚀 Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run build check
        run: pnpm build

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/jdncst-portfolio
            git pull
            docker-compose up -d --build --remove-orphans
